### ISSUE TITLE
Typings for default section

### ISSUE THREAD

**Issue by pacokwon** [shangerxin/config-ini#15] opened 2021-03-29 11:48 UTC
I'm trying out the library with Typescript. It seems like accessing the default section requires one to pass `null` to methods like `items()` and `get()`. Maybe the type definition needs to include `null` as well?

![image](https://user-images.githubusercontent.com/31656049/112832267-0667df00-90d0-11eb-8d64-f6948714175f.png)

**Comment by shangerxin** [comment] 2021-03-30 08:54
Hi @pacokwon 

Got it. The issue is fixed in the new release 1.5.1. Please verify the result. Thank you for the valuable feedbacks. 

Best regards, 
Edwin

**Closed** 2021-03-30 08:54 UTC
Labels: bug
